services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alpine-api
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8081:8081"

    environment:
      PORT: 8081
      BASE_URL: /api/v1
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 7d

    volumes:
      - /var/www/alpine-uploads:/var/www/alpine-uploads

    networks:
      - alpine-network

networks:
  alpine-network:
    external: true
